services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the downloads folder to persist crawled data on your local machine
      - ./backend_api/downloads:/app/downloads
    env_file:
      # Load environment variables from the .env file located in the backend_api directory
      - ./backend_api/.env 